### ISSUE TITLE
events fire before images have loaded

### ISSUE THREAD

**Issue by pacu** [homerjam/angular-images-loaded#11]
images of a container are still loaded but the event already fired. 

using angular 1.4.8
imagesloaded 4.1.0
and latest of this directive.

happens on dev, on prod both chrome and safari

**Comment by homerjam** [comment]
Hi @pacu, could you show some code please? A plunkr/fiddle would be useful.

**Comment by pacu** [comment]
@homerjam sure. I'd need images from a service to recreate the situation on a plunkr so I'll try with code first.

**Context:** This is a image matching game, for a e-learning platform. there are two image carousels side by side and the user needs to match 2 of them. There are images that are served statically from the web server and others that come from a service. the responses are quite big and but the image quality is very important for the purpose of the platform. _There are some overlays for these images and re-scaling of resources to be done once the images are rendered on the screen._ that's why I need to know when the images have been loaded completely.  

**HTML file**
```
<!-- Wrapper for slides -->
                            <div id="pl-satellite-slides-carrousel" class="carousel-inner vertical" role="listbox" images-loaded="carrouselSatelliteLoaded">
                                <div id="{{'satellite-'+$index}}" ng-repeat="sPhoto in exercise.satelliteSlides track by sPhoto.id" ng-class="{item : true, active : $first , 'pl-satellite-image' : true}">

                                    <img ng-src="{{sPhoto.satelliteImage.image.hiResImagePath}}">
                                    <div class="pl-compass">
                                        <img src="assets/images/compass_4.png" class="img-responsive"></img>

                                    </div>
                                    <div class="scale-meter">
                                        <scale-meter ng-if="showScales" id="{{'satellite-scale-'+$index}}" properties="sPhoto.scaleProperties" width="394" height="20"></scale-meter>
                                    </div>
                                </div>
                                <div class="pl-result-overlay pl-overlay-wrong center" ng-show="showPairingResult && !pairResultOk">
                                    <div class="pl-overlay-sign pl-wrong center">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    </div>
                                </div>
                                <div class="pl-result-overlay pl-overlay-correct center" ng-show="showPairingResult && pairResultOk">
                                    <div class="pl-overlay-sign pl-correct center">
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                    </div>
                                </div>

                            </div>
```

**controller.js**
  ```
$scope.carrouselSatelliteLoaded = {
            always: function(instance) {
                // Do stuff
            },

            done: function(instance) {

                console.log('pl-satellite-slides-carrousel LOADED');


            },

            fail: function(instance) {
                // Do stuff
                console.log("pl-satellite-slides-carrousel LOADED FAILED");
            }
        };
```

**Comment by homerjam** [comment]
I'm on my phone so can't look properly but a couple of thoughts - can you
try using ng-src for all images. And are the images progressive jpegs? I
wonder if that could be a factor...

On 9 Dec 2016 6:46 p.m., "Francisco Gindre" <notifications@github.com>
wrote:

@homerjam <https://github.com/homerjam> sure. I'd need images from a
service to recreate the situation on a plunkr so I'll try with code first.

*Context:* This is a image matching game, for a e-learning platform. there
are two image carousels side by side and the user needs to match 2 of them.
There are images that are served statically from the web server and others
that come from a service. the responses are quite big and but the image
quality is very important for the purpose of the platform. *There are some
overlays for these images and re-scaling of resources to be done once the
images are rendered on the screen.* that's why I need to know when the
images have been loaded completely.

*HTML file*


                            <div id="pl-satellite-slides-carrousel"
class="carousel-inner vertical" role="listbox"
images-loaded="carrouselSatelliteLoaded">
                                <div id="{{'satellite-'+$index}}"
ng-repeat="sPhoto in exercise.satelliteSlides track by sPhoto.id"
ng-class="{item : true, active : $first , 'pl-satellite-image' :
true}">

                                    <img
ng-src="{{sPhoto.satelliteImage.image.hiResImagePath}}">
                                    <div class="pl-compass">
                                        <img
src="assets/images/compass_4.png" class="img-responsive"></img>

                                    </div>
                                    <div class="scale-meter">
                                        <scale-meter
ng-if="showScales" id="{{'satellite-scale-'+$index}}"
properties="sPhoto.scaleProperties" width="394"
height="20"></scale-meter>
                                    </div>
                                </div>
                                <div class="pl-result-overlay
pl-overlay-wrong center" ng-show="showPairingResult && !pairResultOk">
                                    <div class="pl-overlay-sign
pl-wrong center">
                                        <span class="glyphicon
glyphicon-remove" aria-hidden="true"></span>
                                    </div>
                                </div>
                                <div class="pl-result-overlay
pl-overlay-correct center" ng-show="showPairingResult &&
pairResultOk">
                                    <div class="pl-overlay-sign
pl-correct center">
                                        <span class="glyphicon
glyphicon-ok" aria-hidden="true"></span>
                                    </div>
                                </div>

                            </div>

*controller.js*

$scope.carrouselSatelliteLoaded = {
          always: function(instance) {
              // Do stuff
          },

          done: function(instance) {

              console.log('pl-satellite-slides-carrousel LOADED');


          },

          fail: function(instance) {
              // Do stuff
              console.log("pl-satellite-slides-carrousel LOADED FAILED");
          }
      };

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/homerjam/angular-images-loaded/issues/11#issuecomment-266090135>,
or mute the thread

**Comment by pacu** [comment]
**I found the problem** I had a typo on several images and the <img > did not have the ending /

this made the DOM render but the directive to fail and to work only with the static images that where  correctly tagged

**Comment by homerjam** [comment]
Glad you figured it out!

**Comment by pacu** [comment]
@homerjam It was a false positive. I can still see the same issue as before regardless having a well-formed html now.

The JPEGs I'm loading are not progressive but the PNGs are actually interlaced  now that you mentioned it.

I'll try to remove those and give you an update

**Comment by homerjam** [comment]
Ok. The quickest way to resolve will be creating a live example - I believe the problem probably originates outside of the scope of this plugin. You can use https://placehold.it/ or http://lorempixel.com/ for images.

**Comment by pacu** [comment]
@homerjam  I suck at plunkr so I don't know how to include angular-images-loaded.
https://plnkr.co/edit/SqMauzKWUetm34p6VLWr?p=info

**Comment by homerjam** [comment]
I've added angular-images-loaded via rawgit. I've also updated your plunkr to show the plugin working (even with failing images). Possibly you've misunderstood how images-loaded works?

https://plnkr.co/edit/IEOFXDoXCPQv0gCY92Oc?p=preview

**Comment by pacu** [comment]
> Possibly you've misunderstood how images-loaded works?
I wouldn't discard that option either. I'm replicating this on my project to see what happens. 
thanks
